### ISSUE TITLE
Project bootstrap

### ISSUE THREAD

**Issue by sergeyt** [edu-xored/calendar#1]
## TODO
* [ ] typings are managed with TypeScript 2.0, no separate tool is required, npm is enough now
* [ ] express.js server with one testing GET route
* [ ] empty frontend with two pages (one for not found route)
* [ ] simple mocha test
* [ ] travis integration (for now just check that code is compilable)
